apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "helloworld"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: "helloworld"
  template:
    metadata:
      labels:
        app: "helloworld"
    spec:
      initContainers:
      - name: check-webapp-ready
        image: gwiersma/busybox
        volumeMounts:
        - name: storage01
          mountPath: /www
      containers:
      - name: webserver
        image: "dockercloud/hello-world:latest"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: storage01
          mountPath: /www
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 3
      volumes:
      - name: storage01
        persistentVolumeClaim:
          claimName: storage01
