apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "helloworld"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "helloworld"

  template:
    metadata:
      labels:
        app: "helloworld"

    spec:
      volumes:
        - name: "application"
          hostPath:
            path: /var/kube/workdir/
            type: DirectoryOrCreate
      initContainers:
      - name: check-webapp-ready
        image: busybox
        command: ["wget", "-O", "/www/index.php", "http://10.10.10.92/index.php"]
        volumeMounts:
          - name: "application"
            mountPath: "/www"
      containers:
      - name: webserver
        image: "dockercloud/hello-world"
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name: "application"
            mountPath: "/www"
